In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import os

In [14]:
path = "../data/"
train_path = os.path.join(path, "train.csv")
test_path = os.path.join(path, "test.csv")

train = pd.read_csv(train_path, encoding='utf-8')
test = pd.read_csv(test_path, encoding='utf-8')
display(train.head())
print(list(train.columns))

,ID,gender,age,height,weight,cholesterol,systolic_blood_pressure,diastolic_blood_pressure,glucose,bone_density,activity,smoke_status,medical_history,family_medical_history,sleep_pattern,edu_level,mean_working,stress_score
0,TRAIN_0000,F,72,161.49,58.47,279.84,165,100,143.35,0.87,moderate,ex-smoker,high blood pressure,diabetes,sleep difficulty,bachelors degree,NaN,0.63
1,TRAIN_0001,M,88,179.87,77.60,257.37,178,111,146.94,0.07,moderate,ex-smoker,NaN,diabetes,normal,graduate degree,NaN,0.83
2,TRAIN_0002,M,47,182.47,89.93,226.66,134,95,142.61,1.18,light,ex-smoker,NaN,NaN,normal,high school diploma,9.0,0.70
3,TRAIN_0003,M,69,185.78,68.63,206.74,158,92,137.26,0.48,intense,ex-smoker,high blood pressure,NaN,oversleeping,graduate degree,NaN,0.17
4,TRAIN_0004,F,81,164.63,71.53,255.92,171,116,129.37,0.34,moderate,ex-smoker,diabetes,diabetes,sleep difficulty,bachelors degree,NaN,0.36

['ID', 'gender', 'age', 'height', 'weight', 'cholesterol', 'systolic_blood_pressure', 'diastolic_blood_pressure', 'glucose', 'bone_density', 'activity', 'smoke_status', 'medical_history', 'family_medical_history', 'sleep_pattern', 'edu_level', 'mean_working', 'stress_score']

In [9]:
train['BMI'] = round(train['weight']*10000 / (train['height'] ** 2),1)
train['BMI']

0       22.4
1       24.0
2       27.0
3       19.9
4       26.4
        ...
2995    25.4
2996    17.6
2997    21.1
2998    25.0
2999    21.5
Name: BMI, Length: 3000, dtype: float64

In [12]:
train.describe()

,age,height,weight,cholesterol,systolic_blood_pressure,diastolic_blood_pressure,glucose,bone_density,mean_working,stress_score,BMI
count,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,1968.000000,3000.000000,3000.000000
mean,53.06800,168.585687,72.486680,233.910523,146.144333,95.504000,126.467720,0.933367,8.716972,0.482130,25.534300
std,20.67207,9.351876,13.167222,24.333434,15.845310,9.895283,18.536844,0.444783,1.628944,0.288252,4.359816
min,17.00000,141.130000,36.320000,148.810000,97.000000,60.000000,70.050000,-0.220000,4.000000,0.000000,12.100000
25%,35.00000,161.800000,63.035000,216.927500,135.000000,89.000000,113.912500,0.560000,8.000000,0.230000,22.400000
50%,53.00000,168.115000,71.240000,234.255000,146.000000,95.000000,126.555000,0.940000,9.000000,0.480000,25.300000
75%,72.00000,175.352500,81.832500,250.377500,158.000000,102.000000,139.180000,1.300000,10.000000,0.730000,28.400000
max,89.00000,195.280000,120.880000,313.350000,191.000000,124.000000,185.740000,2.000000,16.000000,1.000000,43.400000

In [13]:
def bmi_category(bmi):
    """성인 기준 WHO BMI 판정 함수"""
    if bmi < 18.5:
        return "underweight"
    elif 18.5 <= bmi < 25:
        return "normal"
    elif 25 <= bmi < 30:
        return "overweight"
    elif 30 <= bmi < 35:
        return "obesity class I"
    elif 35 <= bmi < 40:
        return "obesity class II"
    else:
        return "obesity class III"

train['BMI_category'] = train["BMI"].apply(lambda x: bmi_category(x))
train

,ID,gender,age,height,weight,cholesterol,systolic_blood_pressure,diastolic_blood_pressure,glucose,bone_density,activity,smoke_status,medical_history,family_medical_history,sleep_pattern,edu_level,mean_working,stress_score,BMI,BMI_category
0,TRAIN_0000,F,72,161.49,58.47,279.84,165,100,143.35,0.87,moderate,ex-smoker,high blood pressure,diabetes,sleep difficulty,bachelors degree,NaN,0.63,22.4,normal
1,TRAIN_0001,M,88,179.87,77.60,257.37,178,111,146.94,0.07,moderate,ex-smoker,NaN,diabetes,normal,graduate degree,NaN,0.83,24.0,normal
2,TRAIN_0002,M,47,182.47,89.93,226.66,134,95,142.61,1.18,light,ex-smoker,NaN,NaN,normal,high school diploma,9.0,0.70,27.0,overweight
3,TRAIN_0003,M,69,185.78,68.63,206.74,158,92,137.26,0.48,intense,ex-smoker,high blood pressure,NaN,oversleeping,graduate degree,NaN,0.17,19.9,normal
4,TRAIN_0004,F,81,164.63,71.53,255.92,171,116,129.37,0.34,moderate,ex-smoker,diabetes,diabetes,sleep difficulty,bachelors degree,NaN,0.36,26.4,overweight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,TRAIN_2995,F,87,174.43,77.14,233.31,176,111,134.71,0.20,light,non-smoker,NaN,NaN,oversleeping,NaN,NaN,0.02,25.4,overweight
2996,TRAIN_2996,M,25,171.44,51.67,196.89,143,86,111.91,1.75,moderate,current-smoker,NaN,NaN,normal,high school diploma,9.0,0.16,17.6,underweight
2997,TRAIN_2997,F,54,162.13,55.54,210.52,164,91,136.47,0.80,light,current-smoker,NaN,NaN,normal,NaN,9.0,0.16,21.1,normal
2998,TRAIN_2998,M,70,181.32,82.20,234.10,182,91,144.89,0.58,moderate,non-smoker,NaN,NaN,oversleeping,high school diploma,NaN,0.18,25.0,overweight
2999,TRAIN_2999,M,86,179.46,69.31,254.63,149,94,154.92,0.45,moderate,ex-smoker,high blood pressure,heart disease,normal,NaN,NaN,0.04,21.5,normal

In [18]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# 차원축소에 사용할 컬럼 선택
pca_features = [
    "cholesterol",
    "systolic_blood_pressure",
    "diastolic_blood_pressure",
    "glucose",
    "bone_density"
]

# 스케일링 (PCA는 스케일 차이에 민감함)
scaler = StandardScaler()
scaled_train = scaler.fit_transform(train[pca_features])
scaled_test = scaler.transform(test[pca_features])

# PCA: 2차원으로 축소
pca = PCA(n_components=3, random_state=42)
train_pca = pca.fit_transform(scaled_train)
test_pca = pca.transform(scaled_test)

# 결과를 데이터프레임에 합치기
train["health_pca1"] = train_pca[:, 0]
train["health_pca2"] = train_pca[:, 1]
train["health_pca3"] = train_pca[:, 2]
test["health_pca1"] = test_pca[:, 0]
test["health_pca2"] = test_pca[:, 1]
test["health_pca3"] = test_pca[:, 2]

print("PCA 설명 분산 비율:", pca.explained_variance_ratio_)

PCA 설명 분산 비율: [0.50547296 0.1577627  0.15337087]

In [19]:
train

,ID,gender,age,height,weight,cholesterol,systolic_blood_pressure,diastolic_blood_pressure,glucose,bone_density,...,smoke_status,medical_history,family_medical_history,sleep_pattern,edu_level,mean_working,stress_score,health_pca1,health_pca2,health_pca3
0,TRAIN_0000,F,72,161.49,58.47,279.84,165,100,143.35,0.87,...,ex-smoker,high blood pressure,diabetes,sleep difficulty,bachelors degree,NaN,0.63,-1.860469,-0.634588,0.999613
1,TRAIN_0001,M,88,179.87,77.60,257.37,178,111,146.94,0.07,...,ex-smoker,NaN,diabetes,normal,graduate degree,NaN,0.83,-3.484464,0.117124,-0.416231
2,TRAIN_0002,M,47,182.47,89.93,226.66,134,95,142.61,1.18,...,ex-smoker,NaN,NaN,normal,high school diploma,9.0,0.70,0.476168,0.776218,0.712207
3,TRAIN_0003,M,69,185.78,68.63,206.74,158,92,137.26,0.48,...,ex-smoker,high blood pressure,NaN,oversleeping,graduate degree,NaN,0.17,-0.554966,1.282035,-0.626455
4,TRAIN_0004,F,81,164.63,71.53,255.92,171,116,129.37,0.34,...,ex-smoker,diabetes,diabetes,sleep difficulty,bachelors degree,NaN,0.36,-2.808723,-0.595927,-0.934962
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,TRAIN_2995,F,87,174.43,77.14,233.31,176,111,134.71,0.20,...,non-smoker,NaN,NaN,oversleeping,NaN,NaN,0.02,-2.663933,0.325021,-1.300249
2996,TRAIN_2996,M,25,171.44,51.67,196.89,143,86,111.91,1.75,...,current-smoker,NaN,NaN,normal,high school diploma,9.0,0.16,2.389860,0.552352,-0.684058
2997,TRAIN_2997,F,54,162.13,55.54,210.52,164,91,136.47,0.80,...,current-smoker,NaN,NaN,normal,NaN,9.0,0.16,-0.327755,1.166079,-0.573888
2998,TRAIN_2998,M,70,181.32,82.20,234.10,182,91,144.89,0.58,...,non-smoker,NaN,NaN,oversleeping,high school diploma,NaN,0.18,-1.647394,0.889867,-0.240422
2999,TRAIN_2999,M,86,179.46,69.31,254.63,149,94,154.92,0.45,...,ex-smoker,high blood pressure,heart disease,normal,NaN,NaN,0.04,-1.484520,0.537036,1.236907